M48
; DRILL file {KiCad (6.0.0)} date Thu Jan 13 15:12:21 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-01-13T15:12:21+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X5.2602Y-2.8264
X5.2602Y-4.8736
X7.3075Y-2.8264
X7.3075Y-4.8736
T0
M30
