M48
; DRILL file {KiCad (6.0.0)} date Thu Mar  3 17:00:35 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-03-03T17:00:35+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0630
%
G90
G05
T1
X5.3911Y-2.7577
T2
X4.5949Y-3.6067
X5.9015Y-3.6067
T1
G00X5.1136Y-2.7577
M15
G01X5.1018Y-2.7577
M16
G05
T0
M30
