M48
; DRILL file {KiCad (6.0.0)} date Fri Mar  4 19:12:45 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-03-04T19:12:45+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.600
%
G90
G05
T1
X136.935Y-70.045
T2
X116.709Y-91.611
X149.899Y-91.611
T1
G00X129.885Y-70.045
M15
G01X129.585Y-70.045
M16
G05
T0
M30
