M48
; DRILL file {KiCad (6.0.4)} date Wed Jul  6 17:34:38 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-07-06T17:34:38+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X167.44Y-62.86
X167.44Y-80.86
X167.44Y-93.11
X167.44Y-111.11
T2
X114.8Y-61.6
X114.8Y-112.9
X167.4Y-87.2
T0
M30
